# FROM python:3.7-slim
# WORKDIR /app/
# COPY requirements.txt /app/
# RUN pip install -r requirements.txt
# COPY main.py /app/
# EXPOSE 443
# CMD [ "python", "main.py" ]

FROM python:3.7-slim

WORKDIR /app/

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY main.py /app/
COPY cert.pem /app/
COPY key.pem /app/

EXPOSE 443

CMD ["python", "main.py"]
